#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright Hersel Giannella <www.hersel.it>

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/usr/bin/firefox')
driver = webdriver.Firefox(firefox_binary=binary)

driver.get("https://www.yoursite/login")#put here the adress of your page
driver.find_element_by_id("Email").send_keys("insert email")
driver.find_element_by_id ("Password").send_keys("insert_password")
driver.find_element_by_class_name('customButtonA').click()

#If I want to close the Selenium session
#driver.close()
